const allRides = [
  {
    id: 1,
    driver: "Faiyaz Shaikh",
    distance: "5 kms away",
    rating: 3,
    route: "Christ University to Trinity Metro",
    start: "Christ University",
    end: "Trinity Metro",
    car: "Muscle",
    seats: 2,
    image: "/imgR.jpg",
    pickupPoint: "Main Gate, Christ University",
  },
  {
    id: 2,
    driver: "Gian",
    distance: "15 kms away",
    rating: 2,
    route: "Kengeri to MG Road",
    start: "Kengeri",
    end: "MG Road",
    car: "Toyota",
    seats: 2,
    image: "/img5.webp",
    pickupPoint: "Kengeri Bus Station",
  },
  {
    id: 3,
    driver: "Doraemon",
    distance: "18 kms away",
    rating: 4.5,
    route: "Indiranagar to Whitefield",
    start: "Indiranagar",
    end: "Whitefield",
    car: "Honda",
    seats: 3,
    image: "/imgr1.jpg",
    pickupPoint: "Indiranagar Metro Station",
  },
  {
    id: 4,
    driver: "Nobita",
    distance: "22 kms away",
    rating: 3,
    route: "Hebbal to Banashankari",
    start: "Hebbal",
    end: "Banashankari",
    car: "Honda",
    seats: 2,
    image: "/imgR.jpg",
    pickupPoint: "Hebbal Lake",
  },
  {
    id: 5,
    driver: "Thomas Kinkade",
    distance: "30 kms away",
    rating: 3.5,
    route: "Koramangala to Yelahanka",
    start: "Koramangala",
    end: "Yelahanka",
    car: "BMW",
    seats: 5,
    image: "/imgr1.jpg",
    pickupPoint: "Koramangala 1st Block",
  },
  {
    id: 6,
    driver: "Sonia Sharma",
    distance: "8 kms away",
    rating: 4.7,
    route: "Marathahalli to Sarjapur",
    start: "Marathahalli",
    end: "Sarjapur",
    car: "Audi",
    seats: 4,
    image: "/imgR.jpg",
    pickupPoint: "Marathahalli Bridge",
  },
  {
    id: 7,
    driver: "Aman Gupta",
    distance: "10 kms away",
    rating: 4.0,
    route: "Kormangala to BTM Layout",
    start: "Kormangala",
    end: "BTM Layout",
    car: "Mercedes",
    seats: 4,
    image: "/img5.webp",
    pickupPoint: "Kormangala 5th Block",
  },
  {
    id: 8,
    driver: "Ravi Kumar",
    distance: "7 kms away",
    rating: 3.8,
    route: "Jayanagar to JP Nagar",
    start: "Jayanagar",
    end: "JP Nagar",
    car: "Hyundai",
    seats: 3,
    image: "/imgr1.jpg",
    pickupPoint: "Jayanagar 4th Block",
  },
  {
    id: 9,
    driver: "Priya Singh",
    distance: "12 kms away",
    rating: 4.3,
    route: "Electronic City to HSR Layout",
    start: "Electronic City",
    end: "HSR Layout",
    car: "Ford",
    seats: 2,
    image: "/imgR.jpg",
    pickupPoint: "Electronic City Metro Station",
  },
  {
    id: 10,
    driver: "Ajay Mehta",
    distance: "5 kms away",
    rating: 5.0,
    route: "Rajajinagar to Malleshwaram",
    start: "Rajajinagar",
    end: "Malleshwaram",
    car: "Toyota",
    seats: 2,
    image: "/imgr1.jpg",
    pickupPoint: "Rajajinagar 1st Block",
  },
];

export default allRides;
